### ISSUE TITLE
NCCL communication timeouts : unable to mmap ...

### ISSUE THREAD

**Issue by btroussel** [MCG-NJU/MOTIP#52]
Hello,

First, thank you very much for your work on MOTIP! It's a very inspiring project with great perspectives.

Using the new codebase of MOTIP, I encountered a training crash after approximately _3800/5000_ iterations on an 8 V100 GPUs setup. The issue appears to be related to NCCL communication timeouts, with an accompanying error:  
`RuntimeError: unable to mmap ... Cannot allocate memory (12) pytorch`. All GPUs seems to be blocked at 100%, indicating that they are waiting for the next sample from the dataloader, but the dataloader seems to be blocked indefinitely. 

Did you also encounter this bug ? Have you find a solution for this problem ? 

### Environment

- **Codebase:** Original repository code, no modifications.
- **PyTorch version:** 2.5.0  
- **Python version:** 3.12.7  
- **CUDA version:** 12.2  
- **GPU setup:** Multi-GPU distributed training using NCCL backend (8x V100 GPUs).

### Error Logs

The error message is as follows:

> Traceback (most recent call last):
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/multiprocessing/queues.py", line 264, in _feed
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/multiprocessing/reductions.py", line 607, in reduce_storage
    metadata = storage._share_filename_cpu_()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/storage.py", line 437, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/storage.py", line 516, in _share_filename_cpu_  
    return super()._share_filename_cpu_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: unable to mmap 104 bytes from file </torch_1283111_2397924332_222255>: Cannot allocate memory (12)
Traceback (most recent call last):
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/multiprocessing/queues.py", line 264, in _feed
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/multiprocessing/reductions.py", line 607, in reduce_storage
    metadata = storage._share_filename_cpu_()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/storage.py", line 437, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/storage.py", line 516, in _share_filename_cpu_  
    return super()._share_filename_cpu_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: unable to mmap 176 bytes from file </torch_1283111_4039908363_222295>: Cannot allocate memory (12)
[rank4]:[E421 01:04:28.399506394 ProcessGroupNCCL.cpp:616] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600024 milliseconds before timing out.
[rank2]:[E421 01:04:28.401116120 ProcessGroupNCCL.cpp:616] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600039 milliseconds before timing out.
[rank4]:[E421 01:04:28.406274807 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 4] Exception (either an error or timeout) detected by watchdog at work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank2]:[E421 01:04:28.406276290 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 2] Exception (either an error or timeout) detected by watchdog at work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank7]:[E421 01:04:28.436508208 ProcessGroupNCCL.cpp:616] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600036 milliseconds before timing out.
[rank7]:[E421 01:04:28.436907525 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 7] Exception (either an error or timeout) detected by watchdog at work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank6]:[E421 01:04:28.448178600 ProcessGroupNCCL.cpp:616] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600080 milliseconds before timing out.
[rank5]:[E421 01:04:28.448282715 ProcessGroupNCCL.cpp:616] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600070 milliseconds before timing out.
[rank6]:[E421 01:04:28.448560707 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 6] Exception (either an error or timeout) detected by watchdog at work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank5]:[E421 01:04:28.448766469 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 5] Exception (either an error or timeout) detected by watchdog at work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank1]:[E421 01:04:28.489109384 ProcessGroupNCCL.cpp:616] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600091 milliseconds before timing out.
[rank1]:[E421 01:04:28.489493100 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 1] Exception (either an error or timeout) detected by watchdog at work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank6]:[E421 01:04:29.968811585 ProcessGroupNCCL.cpp:1834] [PG ID 0 PG GUID 0(default_pg) Rank 6] Timeout at NCCL work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank6]:[E421 01:04:29.968839188 ProcessGroupNCCL.cpp:630] [Rank 6] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank6]:[E421 01:04:29.968849236 ProcessGroupNCCL.cpp:636] [Rank 6] To avoid data inconsistency, we are taking the entire process down.
[rank6]:[E421 01:04:29.998765386 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 6] Process group watchdog thread terminated with exception: [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600080 milliseconds before timing out.
Exception raised from checkTimeout at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14a54d4f0729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14a54e6b9b5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x279 (0x14a54e6d0099 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x23b (0x14a54e6d9a4b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14a (0x14a54e6db40a in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xd6be0 (0x14a54d14bbe0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #6: <unknown function> + 0x89c02 (0x14a583089c02 in /lib64/libc.so.6)
frame #7: <unknown function> + 0x10ec40 (0x14a58310ec40 in /lib64/libc.so.6)
terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 6] Process group watchdog thread terminated with exception: [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600080 milliseconds before timing out.
Exception raised from checkTimeout at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14a54d4f0729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14a54e6b9b5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x279 (0x14a54e6d0099 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x23b (0x14a54e6d9a4b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14a (0x14a54e6db40a in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xd6be0 (0x14a54d14bbe0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #6: <unknown function> + 0x89c02 (0x14a583089c02 in /lib64/libc.so.6)
frame #7: <unknown function> + 0x10ec40 (0x14a58310ec40 in /lib64/libc.so.6)
Exception raised from ncclCommWatchdog at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14a54d4f0729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14a54e6b9b5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd6bf3b (0x14a54e373f3b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xd6be0 (0x14a54d14bbe0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #4: <unknown function> + 0x89c02 (0x14a583089c02 in /lib64/libc.so.6)
frame #5: <unknown function> + 0x10ec40 (0x14a58310ec40 in /lib64/libc.so.6)
[rank5]:[E421 01:04:29.139300808 ProcessGroupNCCL.cpp:1834] [PG ID 0 PG GUID 0(default_pg) Rank 5] Timeout at NCCL work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank5]:[E421 01:04:29.139350973 ProcessGroupNCCL.cpp:630] [Rank 5] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank5]:[E421 01:04:29.139373368 ProcessGroupNCCL.cpp:636] [Rank 5] To avoid data inconsistency, we are taking the entire process down.
[rank5]:[E421 01:04:29.141333672 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 5] Process group watchdog thread terminated with exception: [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600070 milliseconds before timing out.
Exception raised from checkTimeout at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x154bfadbc729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x154bfbf85b5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x279 (0x154bfbf9c099 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x23b (0x154bfbfa5a4b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14a (0x154bfbfa740a in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xd6be0 (0x154bfaa17be0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #6: <unknown function> + 0x89c02 (0x154c30889c02 in /lib64/libc.so.6)
frame #7: <unknown function> + 0x10ec40 (0x154c3090ec40 in /lib64/libc.so.6)
terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 5] Process group watchdog thread terminated with exception: [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600070 milliseconds before timing out.
Exception raised from checkTimeout at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x154bfadbc729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x154bfbf85b5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x279 (0x154bfbf9c099 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x23b (0x154bfbfa5a4b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14a (0x154bfbfa740a in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xd6be0 (0x154bfaa17be0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #6: <unknown function> + 0x89c02 (0x154c30889c02 in /lib64/libc.so.6)
frame #7: <unknown function> + 0x10ec40 (0x154c3090ec40 in /lib64/libc.so.6)
Exception raised from ncclCommWatchdog at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x154bfadbc729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x154bfbf85b5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd6bf3b (0x154bfbc3ff3b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xd6be0 (0x154bfaa17be0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #4: <unknown function> + 0x89c02 (0x154c30889c02 in /lib64/libc.so.6)
frame #5: <unknown function> + 0x10ec40 (0x154c3090ec40 in /lib64/libc.so.6)
[rank0]:[E421 01:04:30.934157590 ProcessGroupNCCL.cpp:616] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93202, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600041 milliseconds before timing out.
[rank0]:[E421 01:04:30.934629241 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 0] Exception (either an error or timeout) detected by watchdog at work: 93202, last enqueued NCCL work: 93202, last completed NCCL work: 93201.
[rank2]:[E421 01:04:30.128876174 ProcessGroupNCCL.cpp:1834] [PG ID 0 PG GUID 0(default_pg) Rank 2] Timeout at NCCL work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank2]:[E421 01:04:30.128933938 ProcessGroupNCCL.cpp:630] [Rank 2] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank2]:[E421 01:04:30.128945616 ProcessGroupNCCL.cpp:636] [Rank 2] To avoid data inconsistency, we are taking the entire process down.
[rank2]:[E421 01:04:30.130984228 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 2] Process group watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600039 milliseconds before timing out.
Exception raised from checkTimeout at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14ab3e411729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14ab3f5dab5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x279 (0x14ab3f5f1099 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x23b (0x14ab3f5faa4b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14a (0x14ab3f5fc40a in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xd6be0 (0x14ab3e06cbe0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #6: <unknown function> + 0x89c02 (0x14ab73e89c02 in /lib64/libc.so.6)
frame #7: <unknown function> + 0x10ec40 (0x14ab73f0ec40 in /lib64/libc.so.6)
terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 2] Process group watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600039 milliseconds before timing out.
Exception raised from checkTimeout at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14ab3e411729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14ab3f5dab5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x279 (0x14ab3f5f1099 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x23b (0x14ab3f5faa4b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14a (0x14ab3f5fc40a in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xd6be0 (0x14ab3e06cbe0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #6: <unknown function> + 0x89c02 (0x14ab73e89c02 in /lib64/libc.so.6)
frame #7: <unknown function> + 0x10ec40 (0x14ab73f0ec40 in /lib64/libc.so.6)
Exception raised from ncclCommWatchdog at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14ab3e411729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14ab3f5dab5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd6bf3b (0x14ab3f294f3b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xd6be0 (0x14ab3e06cbe0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #4: <unknown function> + 0x89c02 (0x14ab73e89c02 in /lib64/libc.so.6)
frame #5: <unknown function> + 0x10ec40 (0x14ab73f0ec40 in /lib64/libc.so.6)
[rank4]:[E421 01:04:30.144302967 ProcessGroupNCCL.cpp:1834] [PG ID 0 PG GUID 0(default_pg) Rank 4] Timeout at NCCL work: 93201, last enqueued NCCL work: 93201, last completed NCCL work: 93200.
[rank4]:[E421 01:04:30.144359969 ProcessGroupNCCL.cpp:630] [Rank 4] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank4]:[E421 01:04:30.144373934 ProcessGroupNCCL.cpp:636] [Rank 4] To avoid data inconsistency, we are taking the entire process down.
[rank4]:[E421 01:04:30.146291604 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 4] Process group watchdog thread terminated with exception: [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600024 milliseconds before timing out.
Exception raised from checkTimeout at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14a8dba66729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14a8dcc2fb5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x279 (0x14a8dcc46099 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x23b (0x14a8dcc4fa4b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14a (0x14a8dcc5140a in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xd6be0 (0x14a8db6c1be0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #6: <unknown function> + 0x89c02 (0x14a911489c02 in /lib64/libc.so.6)
frame #7: <unknown function> + 0x10ec40 (0x14a91150ec40 in /lib64/libc.so.6)
terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 4] Process group watchdog thread terminated with exception: [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=93201, OpType=BROADCAST, NumelIn=106240, NumelOut=106240, Timeout(ms)=600000) ran for 600024 milliseconds before timing out.
Exception raised from checkTimeout at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14a8dba66729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14a8dcc2fb5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x279 (0x14a8dcc46099 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x23b (0x14a8dcc4fa4b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14a (0x14a8dcc5140a in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xd6be0 (0x14a8db6c1be0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #6: <unknown function> + 0x89c02 (0x14a911489c02 in /lib64/libc.so.6)
frame #7: <unknown function> + 0x10ec40 (0x14a91150ec40 in /lib64/libc.so.6)
Exception raised from ncclCommWatchdog at /lustre/fshomisc/sup/hpe/src/pub/miniforge/24.9.0/pytorch-gpu-2.5.0+py3.12.7+cuda12.2/pytorch-2.5.0/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x14a8dba66729 in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10b1b5e (0x14a8dcc2fb5e in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd6bf3b (0x14a8dc8e9f3b in /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xd6be0 (0x14a8db6c1be0 in /gpfslocalsup/spack_soft/gcc/10.1.0/gcc-11.3.1-zpymkx34lriky2mcvx5qyrafvihauhvt/lib64/libstdc++.so.6)
frame #4: <unknown function> + 0x89c02 (0x14a911489c02 in /lib64/libc.so.6)
frame #5: <unknown function> + 0x10ec40 (0x14a91150ec40 in /lib64/libc.so.6)
W0421 01:04:41.327000 1282097 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1282115 closing signal SIGTERM
W0421 01:04:41.336000 1282097 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1282116 closing signal SIGTERM
W0421 01:04:41.337000 1282097 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1282118 closing signal SIGTERM
W0421 01:04:41.337000 1282097 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1282119 closing signal SIGTERM
W0421 01:04:41.338000 1282097 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1282120 closing signal SIGTERM
W0421 01:04:41.338000 1282097 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1282121 closing signal SIGTERM
W0421 01:04:41.339000 1282097 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1282122 closing signal SIGTERM
E0421 01:04:42.370000 1282097 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -6) local_rank: 2 (pid: 1282117) of binary: /lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/bin/python3.12
Traceback (most recent call last):
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fshomisc/sup/hpe/pub/miniforge/24.9.0/envs/pytorch-gpu-2.5.0+py3.12.7/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by HELLORPG** [comment]
May I ask how much RAM your server has?

**Comment by btroussel** [comment]
Yes, the server has about 300 GB of RAM, but it is not even using more than 50GB. I also work with NUM_WORKERS: 2 and PREFETCH_FACTOR: 2 because my server doesn't have much CPUs to go to NUM_WORKERS: 6 and seemed sufficient.

**Comment by HELLORPG** [comment]
I just updated the code to avoid the `Too many open files` error. I suggest you use the latest codebase for testing.

**Comment by btroussel** [comment]
I’ve tried both `pin_memory=False` and `torch.multiprocessing.set_sharing_strategy('file_system')`, but the issue persists. Also, `/dev/shm` has ample available space (~300GB), so it's likely not the bottleneck.

I did find some potentially related issues. One relevant point is a known PyTorch `DataLoader` memory leak when using `multiprocessing` ([discussion](https://github.com/pytorch/pytorch/issues/13246#issuecomment-445446603)). In particular, using nested `dict` or `list` objects may lead to unintentional memory duplication across worker processes. The PyTorch docs also suggest that using contiguous `Tensor` objects or alternatives like `pandas` may help reduce this overhead:  
https://pytorch.org/docs/stable/data.html

That said, addressing this would require some refactoring of my current `DataLoader` structure and I'm not 100% sure it is the problem. In the meantime, I’ll follow your suggestion to remove `torch.multiprocessing.set_sharing_strategy('file_system')` and test whether using `deepcopy` helps mitigate the problem.

Thanks a lot for digging into this — your input is really appreciated! 👍

**Comment by HELLORPG** [comment]
Memory leakage does not seem to be a reasonable cause either. One of my machines has only 377 GB of RAM (just like you, 300 GB), yet it can still run the full training process, and the monitored memory usage has never exceeded 50%.

**Comment by HELLORPG** [comment]
In the new commit, I used `copy.deepcopy()`, which better aligns with the needs of my code. The original use of `.copy` was a mistake :bug: on my part.

You can try the new codebase without using `torch.multiprocessing.set_sharing_strategy('file_system')`. If you have any updates, I’ll reply in the morning -- after I’ve had my moment of triumph over the alarm clock ⏰!

**Comment by btroussel** [comment]
After the `copy.deepcopy()`, it works great !
Thank you very much !

**Comment by HELLORPG** [comment]
I just woke up, and this is great news! Could you let me know if you keep `torch.multiprocessing.set_sharing_strategy('file_system')`?

**Comment by btroussel** [comment]
Yes I removed it and somehow it worked.  (didn't try with tho)

**Comment by HELLORPG** [comment]
Thank you very much! This has greatly helped improve the usability of our code.

BTW, I have two hypotheses:
1. Based on some web search, I found that `torch.multiprocessing.set_sharing_strategy('file_system')` may use `/dev/shm/` to store some data.
2. Using `.copy()` on dict data has caused a memory leak.

I believe it is either one of these two factors or a combined effect of both.

Anyway, thank you so much! At least we've found an effective way.
